### ISSUE TITLE
CRED_SERVICE_ID should be configurable

### ISSUE THREAD

**Issue by bertocco** [opencadc/vos#10]
The CRED_SERVICE_ID in cadc-vos-server/src/main/java/ca/nrc/cadc/vos/server/auth/VOSpaceAuthorizer should be configurable

Proposed patch 

Move CRED_SERVICE_ID in constructor and use localAuthority.getServiceURI:

public class VOSpaceAuthorizer implements Authorizer
{
    protected static final Logger LOG = Logger.getLogger(VOSpaceAuthorizer.class);

```
// TODO: make these configurable or find from the VOSpace capabilities
//private static final String CRED_SERVICE_ID = "ivo://cadc.nrc.ca/cred";
private static String CRED_SERVICE_ID;


 public VOSpaceAuthorizer()
{
    this(false);

    LocalAuthority localAuthority = new LocalAuthority();
    URI serviceURI = localAuthority.getServiceURI(Standards.CRED_DELEGATE_10.toString());
    CRED_SERVICE_ID = serviceURI.toString();

}

public VOSpaceAuthorizer(boolean allowPartialPaths)
{
    initState();
    this.allowPartialPaths = allowPartialPaths;

    LocalAuthority localAuthority = new LocalAuthority();
    URI serviceURI = localAuthority.getServiceURI(Standards.CRED_DELEGATE_10.toString());
    CRED_SERVICE_ID = serviceURI.toString();
}
```

**Comment by brianmajor** [comment]
The VOSpaceAuthorizer should be changed to use the checkCredentials() method from CredUtil.java (in project cadc-cdp-server).  If the call to checkCredentials() returns false, hasMembership() should also return false.  If it returns true, the membership check should continue.

**Comment by brianmajor** [comment]
Fixed.
