### ISSUE TITLE
LinkNodes in cavern

### ISSUE THREAD

**Issue by brianmajor** [opencadc/vos#83]
This issue is to note that preliminary tests from Java and Python clients show that link nodes aren't working in cavern.  More followup and investigation is needed.

**Comment by yeunga** [comment]
For verification of the fix, can execute the test cases in vos/test/scripts/vospace-link-atest.tcsh.

**Comment by brianmajor** [comment]
When this is addressed ,the developer should update the acceptance tests in python vos tools to test link nodes.
